package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Berada generated by hbm2java
 */
public class Berada  implements java.io.Serializable {


     private BeradaId id;
     private Periode periode;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;

    public Berada() {
    }

    public Berada(BeradaId id, Periode periode, Mahasiswa mahasiswa, Matakuliah matakuliah) {
       this.id = id;
       this.periode = periode;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
    }
   
    public BeradaId getId() {
        return this.id;
    }
    
    public void setId(BeradaId id) {
        this.id = id;
    }
    public Periode getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(Periode periode) {
        this.periode = periode;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }




}


