package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * BeradaId generated by hbm2java
 */
public class BeradaId  implements java.io.Serializable {


     private String kodemk;
     private String nim;
     private String idperiode;

    public BeradaId() {
    }

    public BeradaId(String kodemk, String nim, String idperiode) {
       this.kodemk = kodemk;
       this.nim = nim;
       this.idperiode = idperiode;
    }
   
    public String getKodemk() {
        return this.kodemk;
    }
    
    public void setKodemk(String kodemk) {
        this.kodemk = kodemk;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getIdperiode() {
        return this.idperiode;
    }
    
    public void setIdperiode(String idperiode) {
        this.idperiode = idperiode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BeradaId) ) return false;
		 BeradaId castOther = ( BeradaId ) other; 
         
		 return ( (this.getKodemk()==castOther.getKodemk()) || ( this.getKodemk()!=null && castOther.getKodemk()!=null && this.getKodemk().equals(castOther.getKodemk()) ) )
 && ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getIdperiode()==castOther.getIdperiode()) || ( this.getIdperiode()!=null && castOther.getIdperiode()!=null && this.getIdperiode().equals(castOther.getIdperiode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getKodemk() == null ? 0 : this.getKodemk().hashCode() );
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getIdperiode() == null ? 0 : this.getIdperiode().hashCode() );
         return result;
   }   


}


