package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Biayakuliah generated by hbm2java
 */
public class Biayakuliah  implements java.io.Serializable {


     private BiayakuliahId id;
     private Departemen departemen;
     private Integer biayatetap;
     private Integer biayasks;
     private Integer biayaprak;
     private Integer biayaadmin;
     private Set<Pembayaran> pembayarans = new HashSet<Pembayaran>(0);

    public Biayakuliah() {
    }

	
    public Biayakuliah(BiayakuliahId id, Departemen departemen) {
        this.id = id;
        this.departemen = departemen;
    }
    public Biayakuliah(BiayakuliahId id, Departemen departemen, Integer biayatetap, Integer biayasks, Integer biayaprak, Integer biayaadmin, Set<Pembayaran> pembayarans) {
       this.id = id;
       this.departemen = departemen;
       this.biayatetap = biayatetap;
       this.biayasks = biayasks;
       this.biayaprak = biayaprak;
       this.biayaadmin = biayaadmin;
       this.pembayarans = pembayarans;
    }
   
    public BiayakuliahId getId() {
        return this.id;
    }
    
    public void setId(BiayakuliahId id) {
        this.id = id;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }
    public Integer getBiayatetap() {
        return this.biayatetap;
    }
    
    public void setBiayatetap(Integer biayatetap) {
        this.biayatetap = biayatetap;
    }
    public Integer getBiayasks() {
        return this.biayasks;
    }
    
    public void setBiayasks(Integer biayasks) {
        this.biayasks = biayasks;
    }
    public Integer getBiayaprak() {
        return this.biayaprak;
    }
    
    public void setBiayaprak(Integer biayaprak) {
        this.biayaprak = biayaprak;
    }
    public Integer getBiayaadmin() {
        return this.biayaadmin;
    }
    
    public void setBiayaadmin(Integer biayaadmin) {
        this.biayaadmin = biayaadmin;
    }
    public Set<Pembayaran> getPembayarans() {
        return this.pembayarans;
    }
    
    public void setPembayarans(Set<Pembayaran> pembayarans) {
        this.pembayarans = pembayarans;
    }




}


