package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * BiayakuliahId generated by hbm2java
 */
public class BiayakuliahId  implements java.io.Serializable {


     private int angkatan;
     private String kodedept;

    public BiayakuliahId() {
    }

    public BiayakuliahId(int angkatan, String kodedept) {
       this.angkatan = angkatan;
       this.kodedept = kodedept;
    }
   
    public int getAngkatan() {
        return this.angkatan;
    }
    
    public void setAngkatan(int angkatan) {
        this.angkatan = angkatan;
    }
    public String getKodedept() {
        return this.kodedept;
    }
    
    public void setKodedept(String kodedept) {
        this.kodedept = kodedept;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BiayakuliahId) ) return false;
		 BiayakuliahId castOther = ( BiayakuliahId ) other; 
         
		 return (this.getAngkatan()==castOther.getAngkatan())
 && ( (this.getKodedept()==castOther.getKodedept()) || ( this.getKodedept()!=null && castOther.getKodedept()!=null && this.getKodedept().equals(castOther.getKodedept()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAngkatan();
         result = 37 * result + ( getKodedept() == null ? 0 : this.getKodedept().hashCode() );
         return result;
   }   


}


