package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departemen generated by hbm2java
 */
public class Departemen  implements java.io.Serializable {


     private String kodedept;
     private Fakultas fakultas;
     private String namadept;
     private Set<Dosen> dosens = new HashSet<Dosen>(0);
     private Set<Biayakuliah> biayakuliahs = new HashSet<Biayakuliah>(0);
     private Set<Matakuliah> matakuliahs = new HashSet<Matakuliah>(0);

    public Departemen() {
    }

	
    public Departemen(String kodedept, String namadept) {
        this.kodedept = kodedept;
        this.namadept = namadept;
    }
    public Departemen(String kodedept, Fakultas fakultas, String namadept, Set<Dosen> dosens, Set<Biayakuliah> biayakuliahs, Set<Matakuliah> matakuliahs) {
       this.kodedept = kodedept;
       this.fakultas = fakultas;
       this.namadept = namadept;
       this.dosens = dosens;
       this.biayakuliahs = biayakuliahs;
       this.matakuliahs = matakuliahs;
    }
   
    public String getKodedept() {
        return this.kodedept;
    }
    
    public void setKodedept(String kodedept) {
        this.kodedept = kodedept;
    }
    public Fakultas getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(Fakultas fakultas) {
        this.fakultas = fakultas;
    }
    public String getNamadept() {
        return this.namadept;
    }
    
    public void setNamadept(String namadept) {
        this.namadept = namadept;
    }
    public Set<Dosen> getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set<Dosen> dosens) {
        this.dosens = dosens;
    }
    public Set<Biayakuliah> getBiayakuliahs() {
        return this.biayakuliahs;
    }
    
    public void setBiayakuliahs(Set<Biayakuliah> biayakuliahs) {
        this.biayakuliahs = biayakuliahs;
    }
    public Set<Matakuliah> getMatakuliahs() {
        return this.matakuliahs;
    }
    
    public void setMatakuliahs(Set<Matakuliah> matakuliahs) {
        this.matakuliahs = matakuliahs;
    }




}


