package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fakultas generated by hbm2java
 */
public class Fakultas  implements java.io.Serializable {


     private String kodefak;
     private String namafak;
     private Set<Departemen> departemens = new HashSet<Departemen>(0);

    public Fakultas() {
    }

	
    public Fakultas(String kodefak, String namafak) {
        this.kodefak = kodefak;
        this.namafak = namafak;
    }
    public Fakultas(String kodefak, String namafak, Set<Departemen> departemens) {
       this.kodefak = kodefak;
       this.namafak = namafak;
       this.departemens = departemens;
    }
   
    public String getKodefak() {
        return this.kodefak;
    }
    
    public void setKodefak(String kodefak) {
        this.kodefak = kodefak;
    }
    public String getNamafak() {
        return this.namafak;
    }
    
    public void setNamafak(String namafak) {
        this.namafak = namafak;
    }
    public Set<Departemen> getDepartemens() {
        return this.departemens;
    }
    
    public void setDepartemens(Set<Departemen> departemens) {
        this.departemens = departemens;
    }




}


