package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hakakses generated by hbm2java
 */
public class Hakakses  implements java.io.Serializable {


     private String idakses;
     private Integer login;
     private Integer viewabsensi;
     private Integer editabsensi;
     private Integer isifrs;
     private Integer editsyaratfrs;
     private Integer editmkfrs;
     private Integer viewnilai;
     private Integer editnilai;
     private Integer viewkeuangan;
     private Integer editkeuangan;
     private Integer viewpengumuman;
     private Integer editpengumuman;
     private Integer viewjadwal;
     private Integer editjadwal;
     private Integer viewdatamhs;
     private Integer editdatamhs;
     private Integer viewdatadosen;
     private Integer editdatadosen;
     private Integer viewdatastaff;
     private Integer editdatastaff;
     private Integer viewdatamk;
     private Integer editdatamk;
     private Integer editdatahukum;
     private Integer viewperiode;
     private Integer editperiode;
     private Integer viewipk;
     private Integer viewkhs;
     private Integer viewkartuujian;
     private Integer viewtranskrip;
     private Integer viewkrs;
     private Set<Dosen> dosens = new HashSet<Dosen>(0);
     private Set<Staff> staffs = new HashSet<Staff>(0);
     private Set<Mahasiswa> mahasiswas = new HashSet<Mahasiswa>(0);

    public Hakakses() {
    }

	
    public Hakakses(String idakses) {
        this.idakses = idakses;
    }
    public Hakakses(String idakses, Integer login, Integer viewabsensi, Integer editabsensi, Integer isifrs, Integer editsyaratfrs, Integer editmkfrs, Integer viewnilai, Integer editnilai, Integer viewkeuangan, Integer editkeuangan, Integer viewpengumuman, Integer editpengumuman, Integer viewjadwal, Integer editjadwal, Integer viewdatamhs, Integer editdatamhs, Integer viewdatadosen, Integer editdatadosen, Integer viewdatastaff, Integer editdatastaff, Integer viewdatamk, Integer editdatamk, Integer editdatahukum, Integer viewperiode, Integer editperiode, Integer viewipk, Integer viewkhs, Integer viewkartuujian, Integer viewtranskrip, Integer viewkrs, Set<Dosen> dosens, Set<Staff> staffs, Set<Mahasiswa> mahasiswas) {
       this.idakses = idakses;
       this.login = login;
       this.viewabsensi = viewabsensi;
       this.editabsensi = editabsensi;
       this.isifrs = isifrs;
       this.editsyaratfrs = editsyaratfrs;
       this.editmkfrs = editmkfrs;
       this.viewnilai = viewnilai;
       this.editnilai = editnilai;
       this.viewkeuangan = viewkeuangan;
       this.editkeuangan = editkeuangan;
       this.viewpengumuman = viewpengumuman;
       this.editpengumuman = editpengumuman;
       this.viewjadwal = viewjadwal;
       this.editjadwal = editjadwal;
       this.viewdatamhs = viewdatamhs;
       this.editdatamhs = editdatamhs;
       this.viewdatadosen = viewdatadosen;
       this.editdatadosen = editdatadosen;
       this.viewdatastaff = viewdatastaff;
       this.editdatastaff = editdatastaff;
       this.viewdatamk = viewdatamk;
       this.editdatamk = editdatamk;
       this.editdatahukum = editdatahukum;
       this.viewperiode = viewperiode;
       this.editperiode = editperiode;
       this.viewipk = viewipk;
       this.viewkhs = viewkhs;
       this.viewkartuujian = viewkartuujian;
       this.viewtranskrip = viewtranskrip;
       this.viewkrs = viewkrs;
       this.dosens = dosens;
       this.staffs = staffs;
       this.mahasiswas = mahasiswas;
    }
   
    public String getIdakses() {
        return this.idakses;
    }
    
    public void setIdakses(String idakses) {
        this.idakses = idakses;
    }
    public Integer getLogin() {
        return this.login;
    }
    
    public void setLogin(Integer login) {
        this.login = login;
    }
    public Integer getViewabsensi() {
        return this.viewabsensi;
    }
    
    public void setViewabsensi(Integer viewabsensi) {
        this.viewabsensi = viewabsensi;
    }
    public Integer getEditabsensi() {
        return this.editabsensi;
    }
    
    public void setEditabsensi(Integer editabsensi) {
        this.editabsensi = editabsensi;
    }
    public Integer getIsifrs() {
        return this.isifrs;
    }
    
    public void setIsifrs(Integer isifrs) {
        this.isifrs = isifrs;
    }
    public Integer getEditsyaratfrs() {
        return this.editsyaratfrs;
    }
    
    public void setEditsyaratfrs(Integer editsyaratfrs) {
        this.editsyaratfrs = editsyaratfrs;
    }
    public Integer getEditmkfrs() {
        return this.editmkfrs;
    }
    
    public void setEditmkfrs(Integer editmkfrs) {
        this.editmkfrs = editmkfrs;
    }
    public Integer getViewnilai() {
        return this.viewnilai;
    }
    
    public void setViewnilai(Integer viewnilai) {
        this.viewnilai = viewnilai;
    }
    public Integer getEditnilai() {
        return this.editnilai;
    }
    
    public void setEditnilai(Integer editnilai) {
        this.editnilai = editnilai;
    }
    public Integer getViewkeuangan() {
        return this.viewkeuangan;
    }
    
    public void setViewkeuangan(Integer viewkeuangan) {
        this.viewkeuangan = viewkeuangan;
    }
    public Integer getEditkeuangan() {
        return this.editkeuangan;
    }
    
    public void setEditkeuangan(Integer editkeuangan) {
        this.editkeuangan = editkeuangan;
    }
    public Integer getViewpengumuman() {
        return this.viewpengumuman;
    }
    
    public void setViewpengumuman(Integer viewpengumuman) {
        this.viewpengumuman = viewpengumuman;
    }
    public Integer getEditpengumuman() {
        return this.editpengumuman;
    }
    
    public void setEditpengumuman(Integer editpengumuman) {
        this.editpengumuman = editpengumuman;
    }
    public Integer getViewjadwal() {
        return this.viewjadwal;
    }
    
    public void setViewjadwal(Integer viewjadwal) {
        this.viewjadwal = viewjadwal;
    }
    public Integer getEditjadwal() {
        return this.editjadwal;
    }
    
    public void setEditjadwal(Integer editjadwal) {
        this.editjadwal = editjadwal;
    }
    public Integer getViewdatamhs() {
        return this.viewdatamhs;
    }
    
    public void setViewdatamhs(Integer viewdatamhs) {
        this.viewdatamhs = viewdatamhs;
    }
    public Integer getEditdatamhs() {
        return this.editdatamhs;
    }
    
    public void setEditdatamhs(Integer editdatamhs) {
        this.editdatamhs = editdatamhs;
    }
    public Integer getViewdatadosen() {
        return this.viewdatadosen;
    }
    
    public void setViewdatadosen(Integer viewdatadosen) {
        this.viewdatadosen = viewdatadosen;
    }
    public Integer getEditdatadosen() {
        return this.editdatadosen;
    }
    
    public void setEditdatadosen(Integer editdatadosen) {
        this.editdatadosen = editdatadosen;
    }
    public Integer getViewdatastaff() {
        return this.viewdatastaff;
    }
    
    public void setViewdatastaff(Integer viewdatastaff) {
        this.viewdatastaff = viewdatastaff;
    }
    public Integer getEditdatastaff() {
        return this.editdatastaff;
    }
    
    public void setEditdatastaff(Integer editdatastaff) {
        this.editdatastaff = editdatastaff;
    }
    public Integer getViewdatamk() {
        return this.viewdatamk;
    }
    
    public void setViewdatamk(Integer viewdatamk) {
        this.viewdatamk = viewdatamk;
    }
    public Integer getEditdatamk() {
        return this.editdatamk;
    }
    
    public void setEditdatamk(Integer editdatamk) {
        this.editdatamk = editdatamk;
    }
    public Integer getEditdatahukum() {
        return this.editdatahukum;
    }
    
    public void setEditdatahukum(Integer editdatahukum) {
        this.editdatahukum = editdatahukum;
    }
    public Integer getViewperiode() {
        return this.viewperiode;
    }
    
    public void setViewperiode(Integer viewperiode) {
        this.viewperiode = viewperiode;
    }
    public Integer getEditperiode() {
        return this.editperiode;
    }
    
    public void setEditperiode(Integer editperiode) {
        this.editperiode = editperiode;
    }
    public Integer getViewipk() {
        return this.viewipk;
    }
    
    public void setViewipk(Integer viewipk) {
        this.viewipk = viewipk;
    }
    public Integer getViewkhs() {
        return this.viewkhs;
    }
    
    public void setViewkhs(Integer viewkhs) {
        this.viewkhs = viewkhs;
    }
    public Integer getViewkartuujian() {
        return this.viewkartuujian;
    }
    
    public void setViewkartuujian(Integer viewkartuujian) {
        this.viewkartuujian = viewkartuujian;
    }
    public Integer getViewtranskrip() {
        return this.viewtranskrip;
    }
    
    public void setViewtranskrip(Integer viewtranskrip) {
        this.viewtranskrip = viewtranskrip;
    }
    public Integer getViewkrs() {
        return this.viewkrs;
    }
    
    public void setViewkrs(Integer viewkrs) {
        this.viewkrs = viewkrs;
    }
    public Set<Dosen> getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set<Dosen> dosens) {
        this.dosens = dosens;
    }
    public Set<Staff> getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
    public Set<Mahasiswa> getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set<Mahasiswa> mahasiswas) {
        this.mahasiswas = mahasiswas;
    }




}


