package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * JadwalhadirId generated by hbm2java
 */
public class JadwalhadirId  implements java.io.Serializable {


     private String nik;
     private String kodemk;
     private String nim;
     private String kodekelas;
     private String kodejadwal;

    public JadwalhadirId() {
    }

    public JadwalhadirId(String nik, String kodemk, String nim, String kodekelas, String kodejadwal) {
       this.nik = nik;
       this.kodemk = kodemk;
       this.nim = nim;
       this.kodekelas = kodekelas;
       this.kodejadwal = kodejadwal;
    }
   
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getKodemk() {
        return this.kodemk;
    }
    
    public void setKodemk(String kodemk) {
        this.kodemk = kodemk;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getKodekelas() {
        return this.kodekelas;
    }
    
    public void setKodekelas(String kodekelas) {
        this.kodekelas = kodekelas;
    }
    public String getKodejadwal() {
        return this.kodejadwal;
    }
    
    public void setKodejadwal(String kodejadwal) {
        this.kodejadwal = kodejadwal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JadwalhadirId) ) return false;
		 JadwalhadirId castOther = ( JadwalhadirId ) other; 
         
		 return ( (this.getNik()==castOther.getNik()) || ( this.getNik()!=null && castOther.getNik()!=null && this.getNik().equals(castOther.getNik()) ) )
 && ( (this.getKodemk()==castOther.getKodemk()) || ( this.getKodemk()!=null && castOther.getKodemk()!=null && this.getKodemk().equals(castOther.getKodemk()) ) )
 && ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getKodekelas()==castOther.getKodekelas()) || ( this.getKodekelas()!=null && castOther.getKodekelas()!=null && this.getKodekelas().equals(castOther.getKodekelas()) ) )
 && ( (this.getKodejadwal()==castOther.getKodejadwal()) || ( this.getKodejadwal()!=null && castOther.getKodejadwal()!=null && this.getKodejadwal().equals(castOther.getKodejadwal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNik() == null ? 0 : this.getNik().hashCode() );
         result = 37 * result + ( getKodemk() == null ? 0 : this.getKodemk().hashCode() );
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getKodekelas() == null ? 0 : this.getKodekelas().hashCode() );
         result = 37 * result + ( getKodejadwal() == null ? 0 : this.getKodejadwal().hashCode() );
         return result;
   }   


}


