package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jadwal generated by hbm2java
 */
public class Jadwal  implements java.io.Serializable {


     private String kodejadwal;
     private Date hari;
     private Date tanggal;
     private Date jam;
     private Set<Jadwalhadir> jadwalhadirs = new HashSet<Jadwalhadir>(0);

    public Jadwal() {
    }

	
    public Jadwal(String kodejadwal) {
        this.kodejadwal = kodejadwal;
    }
    public Jadwal(String kodejadwal, Date hari, Date tanggal, Date jam, Set<Jadwalhadir> jadwalhadirs) {
       this.kodejadwal = kodejadwal;
       this.hari = hari;
       this.tanggal = tanggal;
       this.jam = jam;
       this.jadwalhadirs = jadwalhadirs;
    }
   
    public String getKodejadwal() {
        return this.kodejadwal;
    }
    
    public void setKodejadwal(String kodejadwal) {
        this.kodejadwal = kodejadwal;
    }
    public Date getHari() {
        return this.hari;
    }
    
    public void setHari(Date hari) {
        this.hari = hari;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Date getJam() {
        return this.jam;
    }
    
    public void setJam(Date jam) {
        this.jam = jam;
    }
    public Set<Jadwalhadir> getJadwalhadirs() {
        return this.jadwalhadirs;
    }
    
    public void setJadwalhadirs(Set<Jadwalhadir> jadwalhadirs) {
        this.jadwalhadirs = jadwalhadirs;
    }




}


