package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Jadwalhadir generated by hbm2java
 */
public class Jadwalhadir  implements java.io.Serializable {


     private JadwalhadirId id;
     private Kelas kelas;
     private Jadwal jadwal;
     private Dosen dosen;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Date tanggal;
     private String statuskehadiran;

    public Jadwalhadir() {
    }

	
    public Jadwalhadir(JadwalhadirId id, Kelas kelas, Jadwal jadwal, Dosen dosen, Mahasiswa mahasiswa, Matakuliah matakuliah) {
        this.id = id;
        this.kelas = kelas;
        this.jadwal = jadwal;
        this.dosen = dosen;
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
    }
    public Jadwalhadir(JadwalhadirId id, Kelas kelas, Jadwal jadwal, Dosen dosen, Mahasiswa mahasiswa, Matakuliah matakuliah, Date tanggal, String statuskehadiran) {
       this.id = id;
       this.kelas = kelas;
       this.jadwal = jadwal;
       this.dosen = dosen;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.tanggal = tanggal;
       this.statuskehadiran = statuskehadiran;
    }
   
    public JadwalhadirId getId() {
        return this.id;
    }
    
    public void setId(JadwalhadirId id) {
        this.id = id;
    }
    public Kelas getKelas() {
        return this.kelas;
    }
    
    public void setKelas(Kelas kelas) {
        this.kelas = kelas;
    }
    public Jadwal getJadwal() {
        return this.jadwal;
    }
    
    public void setJadwal(Jadwal jadwal) {
        this.jadwal = jadwal;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getStatuskehadiran() {
        return this.statuskehadiran;
    }
    
    public void setStatuskehadiran(String statuskehadiran) {
        this.statuskehadiran = statuskehadiran;
    }




}


