package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Kelas generated by hbm2java
 */
public class Kelas  implements java.io.Serializable {


     private String kodekelas;
     private String namakelas;
     private Set<Jadwalhadir> jadwalhadirs = new HashSet<Jadwalhadir>(0);

    public Kelas() {
    }

	
    public Kelas(String kodekelas, String namakelas) {
        this.kodekelas = kodekelas;
        this.namakelas = namakelas;
    }
    public Kelas(String kodekelas, String namakelas, Set<Jadwalhadir> jadwalhadirs) {
       this.kodekelas = kodekelas;
       this.namakelas = namakelas;
       this.jadwalhadirs = jadwalhadirs;
    }
   
    public String getKodekelas() {
        return this.kodekelas;
    }
    
    public void setKodekelas(String kodekelas) {
        this.kodekelas = kodekelas;
    }
    public String getNamakelas() {
        return this.namakelas;
    }
    
    public void setNamakelas(String namakelas) {
        this.namakelas = namakelas;
    }
    public Set<Jadwalhadir> getJadwalhadirs() {
        return this.jadwalhadirs;
    }
    
    public void setJadwalhadirs(Set<Jadwalhadir> jadwalhadirs) {
        this.jadwalhadirs = jadwalhadirs;
    }




}


