package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Kelola generated by hbm2java
 */
public class Kelola  implements java.io.Serializable {


     private KelolaId id;
     private Dosen dosen;
     private Periode periode;
     private Matakuliah matakuliah;

    public Kelola() {
    }

    public Kelola(KelolaId id, Dosen dosen, Periode periode, Matakuliah matakuliah) {
       this.id = id;
       this.dosen = dosen;
       this.periode = periode;
       this.matakuliah = matakuliah;
    }
   
    public KelolaId getId() {
        return this.id;
    }
    
    public void setId(KelolaId id) {
        this.id = id;
    }
    public Dosen getDosen() {
        return this.dosen;
    }
    
    public void setDosen(Dosen dosen) {
        this.dosen = dosen;
    }
    public Periode getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(Periode periode) {
        this.periode = periode;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }




}


