package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private Hakakses hakakses;
     private String nama;
     private String password;
     private String ttl;
     private String statusmhs;
     private Set<Nilai> nilais = new HashSet<Nilai>(0);
     private Set<Jadwalhadir> jadwalhadirs = new HashSet<Jadwalhadir>(0);
     private Set<Berada> beradas = new HashSet<Berada>(0);
     private Set<Matakuliah> matakuliahs = new HashSet<Matakuliah>(0);
     private Set<Pembayaran> pembayarans = new HashSet<Pembayaran>(0);

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim, String nama, String password, String ttl, String statusmhs) {
        this.nim = nim;
        this.nama = nama;
        this.password = password;
        this.ttl = ttl;
        this.statusmhs = statusmhs;
    }
    public Mahasiswa(String nim, Hakakses hakakses, String nama, String password, String ttl, String statusmhs, Set<Nilai> nilais, Set<Jadwalhadir> jadwalhadirs, Set<Berada> beradas, Set<Matakuliah> matakuliahs, Set<Pembayaran> pembayarans) {
       this.nim = nim;
       this.hakakses = hakakses;
       this.nama = nama;
       this.password = password;
       this.ttl = ttl;
       this.statusmhs = statusmhs;
       this.nilais = nilais;
       this.jadwalhadirs = jadwalhadirs;
       this.beradas = beradas;
       this.matakuliahs = matakuliahs;
       this.pembayarans = pembayarans;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Hakakses getHakakses() {
        return this.hakakses;
    }
    
    public void setHakakses(Hakakses hakakses) {
        this.hakakses = hakakses;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTtl() {
        return this.ttl;
    }
    
    public void setTtl(String ttl) {
        this.ttl = ttl;
    }
    public String getStatusmhs() {
        return this.statusmhs;
    }
    
    public void setStatusmhs(String statusmhs) {
        this.statusmhs = statusmhs;
    }
    public Set<Nilai> getNilais() {
        return this.nilais;
    }
    
    public void setNilais(Set<Nilai> nilais) {
        this.nilais = nilais;
    }
    public Set<Jadwalhadir> getJadwalhadirs() {
        return this.jadwalhadirs;
    }
    
    public void setJadwalhadirs(Set<Jadwalhadir> jadwalhadirs) {
        this.jadwalhadirs = jadwalhadirs;
    }
    public Set<Berada> getBeradas() {
        return this.beradas;
    }
    
    public void setBeradas(Set<Berada> beradas) {
        this.beradas = beradas;
    }
    public Set<Matakuliah> getMatakuliahs() {
        return this.matakuliahs;
    }
    
    public void setMatakuliahs(Set<Matakuliah> matakuliahs) {
        this.matakuliahs = matakuliahs;
    }
    public Set<Pembayaran> getPembayarans() {
        return this.pembayarans;
    }
    
    public void setPembayarans(Set<Pembayaran> pembayarans) {
        this.pembayarans = pembayarans;
    }




}


