package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Matakuliah generated by hbm2java
 */
public class Matakuliah  implements java.io.Serializable {


     private String kodemk;
     private String namamk;
     private int sks;
     private int semester;
     private String kurikulum;
     private String wajibpilihan;
     private Set<Mahasiswa> mahasiswas = new HashSet<Mahasiswa>(0);
     private Set<Departemen> departemens = new HashSet<Departemen>(0);
     private Set<Jadwalhadir> jadwalhadirs = new HashSet<Jadwalhadir>(0);
     private Set<Nilai> nilais = new HashSet<Nilai>(0);
     private Set<Berada> beradas = new HashSet<Berada>(0);
     private Set<Kelola> kelolas = new HashSet<Kelola>(0);
     private Set<Pembayaran> pembayarans = new HashSet<Pembayaran>(0);
     private Set<Dosen> dosens = new HashSet<Dosen>(0);

    public Matakuliah() {
    }

	
    public Matakuliah(String kodemk, String namamk, int sks, int semester) {
        this.kodemk = kodemk;
        this.namamk = namamk;
        this.sks = sks;
        this.semester = semester;
    }
    public Matakuliah(String kodemk, String namamk, int sks, int semester, String kurikulum, String wajibpilihan, Set<Mahasiswa> mahasiswas, Set<Departemen> departemens, Set<Jadwalhadir> jadwalhadirs, Set<Nilai> nilais, Set<Berada> beradas, Set<Kelola> kelolas, Set<Pembayaran> pembayarans, Set<Dosen> dosens) {
       this.kodemk = kodemk;
       this.namamk = namamk;
       this.sks = sks;
       this.semester = semester;
       this.kurikulum = kurikulum;
       this.wajibpilihan = wajibpilihan;
       this.mahasiswas = mahasiswas;
       this.departemens = departemens;
       this.jadwalhadirs = jadwalhadirs;
       this.nilais = nilais;
       this.beradas = beradas;
       this.kelolas = kelolas;
       this.pembayarans = pembayarans;
       this.dosens = dosens;
    }
   
    public String getKodemk() {
        return this.kodemk;
    }
    
    public void setKodemk(String kodemk) {
        this.kodemk = kodemk;
    }
    public String getNamamk() {
        return this.namamk;
    }
    
    public void setNamamk(String namamk) {
        this.namamk = namamk;
    }
    public int getSks() {
        return this.sks;
    }
    
    public void setSks(int sks) {
        this.sks = sks;
    }
    public int getSemester() {
        return this.semester;
    }
    
    public void setSemester(int semester) {
        this.semester = semester;
    }
    public String getKurikulum() {
        return this.kurikulum;
    }
    
    public void setKurikulum(String kurikulum) {
        this.kurikulum = kurikulum;
    }
    public String getWajibpilihan() {
        return this.wajibpilihan;
    }
    
    public void setWajibpilihan(String wajibpilihan) {
        this.wajibpilihan = wajibpilihan;
    }
    public Set<Mahasiswa> getMahasiswas() {
        return this.mahasiswas;
    }
    
    public void setMahasiswas(Set<Mahasiswa> mahasiswas) {
        this.mahasiswas = mahasiswas;
    }
    public Set<Departemen> getDepartemens() {
        return this.departemens;
    }
    
    public void setDepartemens(Set<Departemen> departemens) {
        this.departemens = departemens;
    }
    public Set<Jadwalhadir> getJadwalhadirs() {
        return this.jadwalhadirs;
    }
    
    public void setJadwalhadirs(Set<Jadwalhadir> jadwalhadirs) {
        this.jadwalhadirs = jadwalhadirs;
    }
    public Set<Nilai> getNilais() {
        return this.nilais;
    }
    
    public void setNilais(Set<Nilai> nilais) {
        this.nilais = nilais;
    }
    public Set<Berada> getBeradas() {
        return this.beradas;
    }
    
    public void setBeradas(Set<Berada> beradas) {
        this.beradas = beradas;
    }
    public Set<Kelola> getKelolas() {
        return this.kelolas;
    }
    
    public void setKelolas(Set<Kelola> kelolas) {
        this.kelolas = kelolas;
    }
    public Set<Pembayaran> getPembayarans() {
        return this.pembayarans;
    }
    
    public void setPembayarans(Set<Pembayaran> pembayarans) {
        this.pembayarans = pembayarans;
    }
    public Set<Dosen> getDosens() {
        return this.dosens;
    }
    
    public void setDosens(Set<Dosen> dosens) {
        this.dosens = dosens;
    }




}


