package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * NilaiId generated by hbm2java
 */
public class NilaiId  implements java.io.Serializable {


     private String nik;
     private String kodemk;
     private String nim;

    public NilaiId() {
    }

    public NilaiId(String nik, String kodemk, String nim) {
       this.nik = nik;
       this.kodemk = kodemk;
       this.nim = nim;
    }
   
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getKodemk() {
        return this.kodemk;
    }
    
    public void setKodemk(String kodemk) {
        this.kodemk = kodemk;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NilaiId) ) return false;
		 NilaiId castOther = ( NilaiId ) other; 
         
		 return ( (this.getNik()==castOther.getNik()) || ( this.getNik()!=null && castOther.getNik()!=null && this.getNik().equals(castOther.getNik()) ) )
 && ( (this.getKodemk()==castOther.getKodemk()) || ( this.getKodemk()!=null && castOther.getKodemk()!=null && this.getKodemk().equals(castOther.getKodemk()) ) )
 && ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNik() == null ? 0 : this.getNik().hashCode() );
         result = 37 * result + ( getKodemk() == null ? 0 : this.getKodemk().hashCode() );
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         return result;
   }   


}


