package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Pembayaran generated by hbm2java
 */
public class Pembayaran  implements java.io.Serializable {


     private PembayaranId id;
     private Biayakuliah biayakuliah;
     private Mahasiswa mahasiswa;
     private Matakuliah matakuliah;
     private Integer statuskeuangan;

    public Pembayaran() {
    }

	
    public Pembayaran(PembayaranId id, Biayakuliah biayakuliah, Mahasiswa mahasiswa, Matakuliah matakuliah) {
        this.id = id;
        this.biayakuliah = biayakuliah;
        this.mahasiswa = mahasiswa;
        this.matakuliah = matakuliah;
    }
    public Pembayaran(PembayaranId id, Biayakuliah biayakuliah, Mahasiswa mahasiswa, Matakuliah matakuliah, Integer statuskeuangan) {
       this.id = id;
       this.biayakuliah = biayakuliah;
       this.mahasiswa = mahasiswa;
       this.matakuliah = matakuliah;
       this.statuskeuangan = statuskeuangan;
    }
   
    public PembayaranId getId() {
        return this.id;
    }
    
    public void setId(PembayaranId id) {
        this.id = id;
    }
    public Biayakuliah getBiayakuliah() {
        return this.biayakuliah;
    }
    
    public void setBiayakuliah(Biayakuliah biayakuliah) {
        this.biayakuliah = biayakuliah;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Matakuliah getMatakuliah() {
        return this.matakuliah;
    }
    
    public void setMatakuliah(Matakuliah matakuliah) {
        this.matakuliah = matakuliah;
    }
    public Integer getStatuskeuangan() {
        return this.statuskeuangan;
    }
    
    public void setStatuskeuangan(Integer statuskeuangan) {
        this.statuskeuangan = statuskeuangan;
    }




}


