package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periode generated by hbm2java
 */
public class Periode  implements java.io.Serializable {


     private String idperiode;
     private Date tanggal;
     private Date tahun;
     private String kegiatan;
     private Set<Berada> beradas = new HashSet<Berada>(0);
     private Set<Kelola> kelolas = new HashSet<Kelola>(0);

    public Periode() {
    }

	
    public Periode(String idperiode, Date tanggal, Date tahun, String kegiatan) {
        this.idperiode = idperiode;
        this.tanggal = tanggal;
        this.tahun = tahun;
        this.kegiatan = kegiatan;
    }
    public Periode(String idperiode, Date tanggal, Date tahun, String kegiatan, Set<Berada> beradas, Set<Kelola> kelolas) {
       this.idperiode = idperiode;
       this.tanggal = tanggal;
       this.tahun = tahun;
       this.kegiatan = kegiatan;
       this.beradas = beradas;
       this.kelolas = kelolas;
    }
   
    public String getIdperiode() {
        return this.idperiode;
    }
    
    public void setIdperiode(String idperiode) {
        this.idperiode = idperiode;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Date getTahun() {
        return this.tahun;
    }
    
    public void setTahun(Date tahun) {
        this.tahun = tahun;
    }
    public String getKegiatan() {
        return this.kegiatan;
    }
    
    public void setKegiatan(String kegiatan) {
        this.kegiatan = kegiatan;
    }
    public Set<Berada> getBeradas() {
        return this.beradas;
    }
    
    public void setBeradas(Set<Berada> beradas) {
        this.beradas = beradas;
    }
    public Set<Kelola> getKelolas() {
        return this.kelolas;
    }
    
    public void setKelolas(Set<Kelola> kelolas) {
        this.kelolas = kelolas;
    }




}


