package com.ithb.model;
// Generated Apr 8, 2013 4:32:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private String nik;
     private Hakakses hakakses;
     private String nama;
     private String alamat;
     private String password;
     private String studi;
     private String pendidikan;

    public Staff() {
    }

	
    public Staff(String nik, String nama, String password) {
        this.nik = nik;
        this.nama = nama;
        this.password = password;
    }
    public Staff(String nik, Hakakses hakakses, String nama, String alamat, String password, String studi, String pendidikan) {
       this.nik = nik;
       this.hakakses = hakakses;
       this.nama = nama;
       this.alamat = alamat;
       this.password = password;
       this.studi = studi;
       this.pendidikan = pendidikan;
    }
   
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public Hakakses getHakakses() {
        return this.hakakses;
    }
    
    public void setHakakses(Hakakses hakakses) {
        this.hakakses = hakakses;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStudi() {
        return this.studi;
    }
    
    public void setStudi(String studi) {
        this.studi = studi;
    }
    public String getPendidikan() {
        return this.pendidikan;
    }
    
    public void setPendidikan(String pendidikan) {
        this.pendidikan = pendidikan;
    }




}


